export const featuredSeoLandingLinks = [
  { slug: "magellan-akademi", eyebrow: "Magellan Akademi" },
  { slug: "boya-merkezi", eyebrow: "Boya Merkezi" },
  { slug: "serigrafi-kullanim-alanlari", eyebrow: "Kullanım Alanları" },
  { slug: "teknik-bilgi-merkezi", eyebrow: "Teknik Bilgi" },
  { slug: "kimyasal-merkezi", eyebrow: "Kimyasal Merkezi" },
  { slug: "serigrafi-hesaplama-araclari", eyebrow: "Hesaplama Araçları" },
  { slug: "serigrafi-wikipedia", eyebrow: "Serigrafi Wikipedia" },
  { slug: "serigrafi-ai", eyebrow: "Serigrafi AI" },
  { slug: "boya-karsilastirmalari", eyebrow: "Karşılaştırmalar" },
  { slug: "pdf-merkezi", eyebrow: "PDF Merkezi" },
  { slug: "organize-sanayi-bolgeleri", eyebrow: "OSB Sistemi" },
  { slug: "magellan-marka-merkezi", eyebrow: "Marka Merkezi" },
  { slug: "serigrafi-boyalari", eyebrow: "Serigrafi Boyaları" },
  { slug: "serigrafi-baski-boyalari", eyebrow: "Baskı Boyaları" },
  { slug: "emprime-baski-boyasi", eyebrow: "Emprime Boya" },
  { slug: "plastisol-boya", eyebrow: "Plastisol Boya" },
  { slug: "pvc-serigrafi-boyasi", eyebrow: "PVC Boya" },
  { slug: "uv-serigrafi-boyasi", eyebrow: "UV Boya" },
  { slug: "su-bazli-serigrafi-boyasi", eyebrow: "Su Bazlı Boya" },
  { slug: "serigrafi-kimyasallari", eyebrow: "Kimyasallar" },
  { slug: "serigrafi-boya-fiyatlari", eyebrow: "Boya Fiyatları" },
  { slug: "toptan-serigrafi-boya", eyebrow: "Toptan Boya" },
  { slug: "serigrafi-baski-boyasi", eyebrow: "Baskı Boyası" },
  { slug: "serigrafi-malzemeleri", eyebrow: "Malzemeler" },
  { slug: "serigrafi-yardimci-kimyasallari", eyebrow: "Yardımcı Kimyasallar" },
  { slug: "emulsiyon", eyebrow: "Emülsiyon" },
  { slug: "inceltici", eyebrow: "İnceltici" },
  { slug: "geciktirici", eyebrow: "Geciktirici" },
  { slug: "sertlestirici", eyebrow: "Sertleştirici" },
  { slug: "serigrafi-nedir", eyebrow: "Serigrafi Nedir?" },
  { slug: "serigrafi-nasil-yapilir", eyebrow: "Nasıl Yapılır?" },
];
