export type ProductDetailPage = {
  slug: string;
  title: string;
  description: string;
  h1: string;
  eyebrow: string;
  focusKeyword: string;
  categorySlug: string;
  categoryLabel: string;
  image: string;
  productType: string;
  color: string;
  shortDescription: string;
  surfaces: string[];
  uses: string[];
  technicalNotes: string[];
  faq: Array<{
    question: string;
    answer: string;
  }>;
  relatedProductSlugs: string[];
  relatedBlogSlugs: string[];
  relatedLandingSlugs: string[];
};

function productDetailPage(
  slug: string,
  name: string,
  categorySlug: string,
  categoryLabel: string,
  image: string,
  productType: string,
  color: string,
  surfaces: string[],
  uses: string[],
  technicalNotes: string[],
  relatedProductSlugs: string[],
  relatedBlogSlugs: string[],
  relatedLandingSlugs: string[]
): ProductDetailPage {
  return {
    slug,
    title: `${name} | Kullanım Alanları ve Teklif | Magellan Boya`,
    description: `${name} kullanım alanları, yüzey uyumu, teknik seçim ve fiyat teklifi için ürün sayfasını inceleyin.`,
    h1: `${name} Kullanım Alanları ve Teknik Tedarik Bilgisi`,
    eyebrow: categoryLabel,
    focusKeyword: name.toLocaleLowerCase("tr-TR"),
    categorySlug,
    categoryLabel,
    image,
    productType,
    color,
    shortDescription: `${name}; ${surfaces.slice(0, 3).join(", ")} gibi yüzeylerde ${uses[0].toLocaleLowerCase("tr-TR")} ihtiyacı için değerlendirilen profesyonel bir Magellan ürün grubudur.`,
    surfaces,
    uses,
    technicalNotes,
    faq: [
      {
        question: `${name} hangi yüzeylerde kullanılır?`,
        answer: `${name}; ${surfaces.join(", ")} gibi yüzeylerde, uygulama koşulları ve beklenen dayanım birlikte değerlendirilerek kullanılabilir.`,
      },
      {
        question: `${name} fiyatı nasıl alınır?`,
        answer:
          "Fiyat; ürün tipi, renk, ambalaj miktarı, yüzey beklentisi ve düzenli alım planına göre netleşir. En doğru teklif için ürün ihtiyacı WhatsApp üzerinden paylaşılmalıdır.",
      },
      {
        question: `${name} için teknik destek veriliyor mu?`,
        answer:
          "Evet. Baskı yüzeyi, hedef renk, elek yapısı, kuruma sistemi ve üretim adedi paylaşıldığında uygun ürün ve yardımcı kimyasal önerisi yapılabilir.",
      },
    ],
    relatedProductSlugs,
    relatedBlogSlugs,
    relatedLandingSlugs,
  };
}

const pvcRelated = [
  "pvc-serigrafi-boyasi-nedir",
  "pvc-boya-kullanim-alanlari",
  "serigrafi-boya-secimi",
];

const plastisolRelated = [
  "plastisol-boya-nedir",
  "tekstil-baski-boyasi-secimi",
  "plastisol-boya-ile-pvc-boya-farki",
];

const uvRelated = [
  "uv-serigrafi-boyasi-nedir",
  "uv-boya-ile-pvc-boya-farki",
  "serigrafi-boya-secimi",
];

const chemicalRelated = [
  "emulsiyon-nasil-kullanilir",
  "serigrafi-kalip-hazirlama",
  "serigrafi-baski-hatalari",
];

const serigrafiBaskiRelated = [
  "serigrafi-boya-secimi",
  "serigrafi-baski-hatalari",
  "serigrafi-boyasi-nasil-inceltilir",
];

const listedSerigrafiProductPages: ProductDetailPage[] = [
  productDetailPage(
    "pvc-bayrak-kirmizi-serigrafi-baski-boyasi",
    "PVC Bayrak Kırmızı Serigrafi Baskı Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/pvc-altin-yaldiz.png",
    "PVC serigrafi baskı boyası",
    "Bayrak kırmızı",
    ["PVC", "plastik", "etiket", "ambalaj", "promosyon", "suni deri"],
    ["Bayrak kırmızı logo baskısı", "PVC ve plastik yüzey işaretleme", "Promosyon ve ambalaj baskısı"],
    ["Kırmızı ton standardı sipariş öncesi netleştirilmelidir.", "Parlak ve esnek PVC yüzeylerde tutunma testi önerilir.", "Seri üretimde viskozite ve kuruma standardı korunmalıdır."],
    ["pvc-kirmizi-serigrafi-boyasi", "pvc-sari-serigrafi-boyasi", "serigrafi-geciktirici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "pvc-baski-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-extra-beyaz-serigrafi-baski-boyasi",
    "PVC Extra Beyaz Serigrafi Baskı Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/pvc-gumus-yaldiz.png",
    "PVC serigrafi baskı boyası",
    "Extra beyaz",
    ["PVC", "plastik", "suni deri", "etiket", "ambalaj", "promosyon"],
    ["Opak beyaz logo baskısı", "Koyu yüzeylerde alt baskı", "PVC yüzeylerde net yazı ve grafik baskısı"],
    ["Beyaz örtücülük beklentisi yüzey rengine göre değerlendirilmelidir.", "Alt baskı ve üst baskı kalınlığı numune ile kontrol edilmelidir.", "Uygun inceltici ve geciktirici seçimi baskı akışını etkiler."],
    ["pvc-beyaz-serigrafi-boyasi", "pvc-siyah-serigrafi-boyasi", "pvc-boya-geciktirici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "pvc-baski-boyasi", "plastik-serigrafi-boyasi"]
  ),
  productDetailPage(
    "pvc-boya-geciktirici",
    "PVC Boya Geciktirici",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "PVC boya geciktirici",
    "Kuruma kontrolü",
    ["PVC baskı", "plastik baskı", "suni deri baskı", "etiket", "ambalaj", "serigrafi kalıbı"],
    ["PVC boyada kuruma süresini kontrol etme", "Kalip tıkanmasını azaltma", "Sıcak ortamda baskı akışını rahatlatma"],
    ["Geciktirici ölçülü kullanılmalıdır.", "Fazla kullanım kuruma ve tutunma performansını değiştirebilir.", "Boya tipi ve ortam sıcaklığına göre küçük deneme önerilir."],
    ["serigrafi-geciktirici", "serigrafi-inceltici", "pvc-extra-beyaz-serigrafi-baski-boyasi"],
    ["geciktirici-ne-ise-yarar", "serigrafi-boyasi-nasil-inceltilir", "serigrafi-baski-hatalari"],
    ["geciktirici", "serigrafi-yardimci-kimyasallari", "pvc-serigrafi-boyasi"]
  ),
  productDetailPage(
    "extra-pvc-boya-geciktirici",
    "Extra PVC Boya Geciktirici",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "PVC boya geciktirici",
    "Extra geciktirici",
    ["PVC baskı", "plastik baskı", "sıcak atölye ortamı", "serigrafi kalıbı", "ambalaj baskı"],
    ["Daha uzun açık kalma süresi isteyen PVC baskılar", "Kalip üzerinde boya kurumasını yavaşlatma", "Seri baskı akışını dengeleme"],
    ["Extra geciktirici yüksek dozda kullanılmamalıdır.", "Uygulama öncesi boya sistemiyle uyumu kontrol edilmelidir.", "Baskı sonrası kuruma süresi üretim planına dahil edilmelidir."],
    ["pvc-boya-geciktirici", "serigrafi-inceltici", "serigrafi-geciktirici"],
    ["geciktirici-ne-ise-yarar", "serigrafi-baski-hatalari", "serigrafi-boyasi-nasil-inceltilir"],
    ["geciktirici", "pvc-serigrafi-boyasi", "serigrafi-kimyasallari"]
  ),
  productDetailPage(
    "dyo-toyo-se-2135-lacivert-serigrafi-murekkebi",
    "Dyo - Toyo SE 2135 Lacivert Serigrafi Mürekkebi",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Dyo Toyo serigrafi mürekkebi",
    "Lacivert",
    ["kağıt", "karton", "etiket", "ambalaj", "plastik", "promosyon"],
    ["Lacivert logo baskısı", "Koyu mavi marka rengi uygulaması", "Ambalaj ve etiket baskısı"],
    ["Lacivert ton standardı numune ile eşleştirilmelidir.", "Yüzey uyumu ve kuruma davranışı baskı öncesi test edilmelidir.", "Tiner ve geciktirici seçimi ürün sistemine göre yapılmalıdır."],
    ["dyo-toyo-se-2400-beyaz-serigrafi-boyasi", "toyo-ink-se-1500-siyah-serigrafi-boyasi", "se-9935-normal-tiner"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "serigrafi-boyalari", "serigrafi-boya-fiyatlari"]
  ),
  productDetailPage(
    "dyo-toyo-se-2400-beyaz-serigrafi-boyasi",
    "Dyo - Toyo SE 2400 Beyaz Serigrafi Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Dyo Toyo serigrafi boyası",
    "Beyaz",
    ["kağıt", "karton", "etiket", "ambalaj", "plastik", "promosyon"],
    ["Beyaz logo ve yazı baskısı", "Alt zemin hazırlığı", "Ambalaj ve etiket yüzeylerinde serigrafi baskı"],
    ["Beyaz baskıda örtücülük beklentisi yüzeye göre değişebilir.", "Koyu zeminlerde numune baskı önerilir.", "Ürün sistemiyle uyumlu tiner kullanılmalıdır."],
    ["dyo-toyo-se-2135-lacivert-serigrafi-murekkebi", "toyo-ink-se-1500-siyah-serigrafi-boyasi", "se-9945-yavaslatici"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "ambalaj-baski-boyasi", "etiket-baski-boyasi"]
  ),
  productDetailPage(
    "dyo-se-2024-bayrak-kirmizi-serigrafi-boyasi",
    "Dyo SE 2024 Bayrak Kırmızı Serigrafi Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Dyo serigrafi boyası",
    "Bayrak kırmızı",
    ["kağıt", "karton", "etiket", "ambalaj", "plastik", "promosyon"],
    ["Bayrak kırmızı marka baskısı", "Uyarı ve dikkat renkli baskı", "Ambalaj üzerinde canlı kırmızı uygulama"],
    ["Kırmızı ton standardı seri üretim öncesi netleştirilmelidir.", "Renk doygunluğu baskı kalınlığıyla birlikte değerlendirilmelidir.", "Numune onayı düzenli alımda fire riskini azaltır."],
    ["dyo-toyo-se-2400-beyaz-serigrafi-boyasi", "toyo-ink-se-1500-siyah-serigrafi-boyasi", "pvc-bayrak-kirmizi-serigrafi-baski-boyasi"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "serigrafi-boya-fiyatlari", "etiket-baski-boyasi"]
  ),
  productDetailPage(
    "toyo-ink-se-1500-siyah-serigrafi-boyasi",
    "Toyo Ink SE 1500 Siyah Serigrafi Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Toyo serigrafi boyası",
    "Siyah",
    ["kağıt", "karton", "etiket", "ambalaj", "plastik", "promosyon"],
    ["Siyah logo ve teknik yazı baskısı", "Etiket ve ambalaj işaretleme", "Net çizgi ve grafik baskısı"],
    ["Siyah baskıda kenar netliği için elek ve rakle ayarı önemlidir.", "Yüzey temizliği tutunma performansını etkileyebilir.", "Boya akışı uygulama hızına göre ayarlanmalıdır."],
    ["dyo-toyo-se-2400-beyaz-serigrafi-boyasi", "dyo-toyo-se-2135-lacivert-serigrafi-murekkebi", "se-9935-normal-tiner"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "ambalaj-baski-boyasi", "serigrafi-boyalari"]
  ),
  productDetailPage(
    "se-9935-normal-tiner",
    "SE 9935 Normal Tiner",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "Serigrafi tineri",
    "Normal tiner",
    ["serigrafi boya", "ambalaj baskı", "etiket baskı", "plastik baskı", "atölye üretimi"],
    ["Boya viskozitesini ayarlama", "Uygulama akışını düzenleme", "Serigrafi baskı hazırlığı"],
    ["Tiner ürün sistemine göre seçilmelidir.", "Fazla inceltme örtücülük ve tutunma performansını düşürebilir.", "Kapalı alanda uygun havalandırma ve güvenlik kuralları uygulanmalıdır."],
    ["serigrafi-inceltici", "se-9945-yavaslatici", "dyo-toyo-se-2400-beyaz-serigrafi-boyasi"],
    ["serigrafi-boyasi-nasil-inceltilir", "serigrafi-baski-hatalari", "serigrafi-boya-secimi"],
    ["inceltici", "serigrafi-yardimci-kimyasallari", "serigrafi-kimyasallari"]
  ),
  productDetailPage(
    "se-9945-yavaslatici",
    "SE 9945 Yavaşlatıcı",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "Serigrafi yavaşlatıcı",
    "Kuruma yavaşlatıcı",
    ["serigrafi boya", "ambalaj baskı", "etiket baskı", "plastik baskı", "sıcak atölye ortamı"],
    ["Kuruma süresini yavaşlatma", "Kalip tıkanmasını azaltma", "Baskı akışını dengeleme"],
    ["Yavaşlatıcı miktarı uygulama koşuluna göre ayarlanmalıdır.", "Fazla kullanım kuruma süresini gereğinden fazla uzatabilir.", "Üretim öncesi küçük baskı testi önerilir."],
    ["serigrafi-geciktirici", "se-9935-normal-tiner", "pvc-boya-geciktirici"],
    ["geciktirici-ne-ise-yarar", "serigrafi-baski-hatalari", "serigrafi-boyasi-nasil-inceltilir"],
    ["geciktirici", "inceltici", "serigrafi-yardimci-kimyasallari"]
  ),
  productDetailPage(
    "sericol-py-021-polyplast-beyaz",
    "Sericol PY 021 Polyplast Beyaz",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Sericol Polyplast serigrafi boyası",
    "Beyaz",
    ["plastik", "PVC", "etiket", "ambalaj", "promosyon", "teknik parça"],
    ["Beyaz plastik yüzey baskısı", "Logo ve yazı uygulaması", "Koyu zeminde beyaz alt baskı"],
    ["Plastik türü ürün seçimini etkiler.", "Beyaz örtücülük beklentisi zemin rengine göre test edilmelidir.", "Yüzey temizliği ve tutunma kontrolü seri üretim öncesi yapılmalıdır."],
    ["sericol-ps-001-black-polyscreen-siyah", "sericol-ps-122-scarlet-polyscreen-kirmizi", "plastik-serigrafi-boyasi"],
    serigrafiBaskiRelated,
    ["plastik-serigrafi-boyasi", "serigrafi-baski-boyasi", "serigrafi-boyalari"]
  ),
  productDetailPage(
    "sericol-ps-122-scarlet-polyscreen-kirmizi",
    "Sericol PS 122 Scarlet Polyscreen Kırmızı",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Sericol Polyscreen serigrafi boyası",
    "Scarlet kırmızı",
    ["plastik", "PVC", "etiket", "ambalaj", "promosyon", "teknik parça"],
    ["Kırmızı marka rengi baskısı", "Promosyon ve etiket uygulaması", "Canlı renkli plastik yüzey baskısı"],
    ["Scarlet ton beklentisi varsa numune ile doğrulanmalıdır.", "Renk doygunluğu baskı kalınlığıyla birlikte değişebilir.", "Yüzeye göre tutunma testi önerilir."],
    ["sericol-py-021-polyplast-beyaz", "sericol-ps-001-black-polyscreen-siyah", "pvc-bayrak-kirmizi-serigrafi-baski-boyasi"],
    serigrafiBaskiRelated,
    ["plastik-serigrafi-boyasi", "etiket-baski-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "sericol-ps-001-black-polyscreen-siyah",
    "Sericol PS 001 Black Polyscreen Siyah",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Sericol Polyscreen serigrafi boyası",
    "Siyah",
    ["plastik", "PVC", "etiket", "ambalaj", "promosyon", "teknik parça"],
    ["Siyah logo ve yazı baskısı", "Teknik işaretleme", "Plastik ve etiket yüzeylerinde net baskı"],
    ["Siyah baskıda detay netliği için elek seçimi önemlidir.", "Boya geçişi ve rakle basıncı birlikte ayarlanmalıdır.", "Yüzey uyumu numune baskıyla kontrol edilmelidir."],
    ["sericol-py-021-polyplast-beyaz", "sericol-ps-122-scarlet-polyscreen-kirmizi", "toyo-ink-se-1500-siyah-serigrafi-boyasi"],
    serigrafiBaskiRelated,
    ["plastik-serigrafi-boyasi", "serigrafi-baski-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "coates-wiederhold-z-60-beyaz",
    "Coates Wiederhold Z 60 Beyaz",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Coates Wiederhold serigrafi boyası",
    "Beyaz",
    ["plastik", "PVC", "etiket", "ambalaj", "panel", "promosyon"],
    ["Beyaz logo ve yazı baskısı", "Teknik panel işaretleme", "Plastik ve ambalaj yüzeylerinde baskı"],
    ["Beyaz ton ve örtücülük numune ile kontrol edilmelidir.", "Z serisi ürünlerde yüzey uyumu baskı öncesi değerlendirilmelidir.", "Kuruma ve tutunma testleri seri üretimden önce yapılmalıdır."],
    ["coates-wiederhold-z-65-siyah", "sericol-py-021-polyplast-beyaz", "dyo-toyo-se-2400-beyaz-serigrafi-boyasi"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "plastik-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "coates-wiederhold-z-65-siyah",
    "Coates Wiederhold Z 65 Siyah",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Coates Wiederhold serigrafi boyası",
    "Siyah",
    ["plastik", "PVC", "etiket", "ambalaj", "panel", "promosyon"],
    ["Siyah logo ve teknik yazı baskısı", "Panel ve etiket işaretleme", "Ambalaj ve promosyon yüzeylerinde net baskı"],
    ["Siyah baskıda çizgi netliği ve örtücülük birlikte değerlendirilmelidir.", "Yüzey enerjisi düşük plastiklerde test baskısı önerilir.", "Üretim temposuna göre viskozite ayarı yapılmalıdır."],
    ["coates-wiederhold-z-60-beyaz", "sericol-ps-001-black-polyscreen-siyah", "toyo-ink-se-1500-siyah-serigrafi-boyasi"],
    serigrafiBaskiRelated,
    ["serigrafi-baski-boyasi", "plastik-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "amex-bi-epoxi-serisi-siyah",
    "AMEX BI-EPOXI Serisi Siyah",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Epoksi serigrafi boyası",
    "Siyah",
    ["metal", "cam", "alüminyum", "endüstriyel panel", "teknik parça", "etiket"],
    ["Cam ve metal yüzeylerde siyah baskı", "Endüstriyel panel işaretleme", "Dayanım beklentisi olan teknik baskı"],
    ["Epoksi sistemlerde karışım ve uygulama standardı önemlidir.", "Yüzey temizliği ve yağ alma tutunmayı doğrudan etkiler.", "Sertleştirici uyumu ve kürlenme koşulu kontrol edilmelidir."],
    ["epoxser-beyaz-rz-101-cam-metal-aluminyum-boyasi", "epoxser-kirmizi-rz-303-cam-metal-boyasi", "zh-sertlestirici"],
    serigrafiBaskiRelated,
    ["metal-serigrafi-boyasi", "cam-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "epoxser-beyaz-rz-101-cam-metal-aluminyum-boyasi",
    "Epoxser Beyaz RZ-101 Cam, Metal ve Alüminyum Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Cam metal epoksi boyası",
    "Beyaz",
    ["cam", "metal", "alüminyum", "etiket", "endüstriyel panel", "teknik parça"],
    ["Cam ve metal üzerinde beyaz baskı", "Alüminyum panel işaretleme", "Dayanım beklentisi olan logo uygulaması"],
    ["Cam ve metal yüzeylerde yağ alma işlemi önemlidir.", "Epoksi karakterli ürünlerde karışım ve kürlenme süreci takip edilmelidir.", "Seri üretimden önce çizilme ve bant testi önerilir."],
    ["amex-bi-epoxi-serisi-siyah", "epoxser-kirmizi-rz-303-cam-metal-boyasi", "epoxer-92-101-beyaz-argon"],
    serigrafiBaskiRelated,
    ["cam-baski-boyasi", "metal-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "epoxser-kirmizi-rz-303-cam-metal-boyasi",
    "Epoxser Kırmızı RZ-303 Cam ve Metal Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Cam metal epoksi boyası",
    "Kırmızı",
    ["cam", "metal", "alüminyum", "etiket", "endüstriyel panel", "teknik parça"],
    ["Cam ve metal üzerinde kırmızı baskı", "Uyarı ve marka rengi uygulaması", "Endüstriyel panel işaretleme"],
    ["Kırmızı ton standardı numune ile doğrulanmalıdır.", "Cam ve metalde yüzey temizliği tutunmayı belirler.", "Kürlenme ve sertleştirici uyumu teknik beklentiye göre değerlendirilmelidir."],
    ["epoxser-beyaz-rz-101-cam-metal-aluminyum-boyasi", "amex-bi-epoxi-serisi-siyah", "dyo-se-2024-bayrak-kirmizi-serigrafi-boyasi"],
    serigrafiBaskiRelated,
    ["cam-baski-boyasi", "metal-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "epoxer-92-101-beyaz-argon",
    "92.101 Epoxer Beyaz Argon",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Argon epoksi serigrafi boyası",
    "Beyaz",
    ["cam", "metal", "alüminyum", "endüstriyel panel", "teknik parça", "etiket"],
    ["Beyaz epoksi baskı", "Cam ve metal panel işaretleme", "Endüstriyel yüzeylerde logo uygulaması"],
    ["Epoksi ürünlerde karışım oranı ve uygulama süresi önemlidir.", "Yüzey hazırlığı yapılmadan seri üretime geçilmemelidir.", "Dayanım beklentisi için çizilme ve tutunma testi önerilir."],
    ["epoxser-beyaz-rz-101-cam-metal-aluminyum-boyasi", "amex-bi-epoxi-serisi-siyah", "zh-sertlestirici"],
    serigrafiBaskiRelated,
    ["metal-serigrafi-boyasi", "cam-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "argon-35-101-beyaz-tampon-baski-boyasi",
    "35-101 Beyaz Argon Tampon Baskı Boyası",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Tampon baskı boyası",
    "Beyaz",
    ["plastik", "metal", "cam", "promosyon", "teknik parça", "küçük yüzeyler"],
    ["Tampon baskıda beyaz logo uygulaması", "Küçük teknik parçalarda işaretleme", "Promosyon ürünlerinde marka baskısı"],
    ["Tampon baskıda klişe, pad ve yüzey uyumu birlikte değerlendirilmelidir.", "Beyaz örtücülük hedef yüzeye göre test edilmelidir.", "Ürün sistemiyle uyumlu tiner kullanılmalıdır."],
    ["dyo-toyo-se-2400-beyaz-serigrafi-boyasi", "epoxer-92-101-beyaz-argon", "se-9935-normal-tiner"],
    serigrafiBaskiRelated,
    ["promosyon-baski-boyasi", "plastik-serigrafi-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "argon-105-101-uv-beyaz-serigrafi-boyasi",
    "105.101 UV Argon Serigrafi Beyaz Boya",
    "uv-serigrafi-boyalari",
    "UV Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "UV serigrafi boyası",
    "Beyaz",
    ["etiket", "ambalaj", "plastik", "cam", "metal", "promosyon"],
    ["UV beyaz logo baskısı", "Hızlı kürlenen etiket ve ambalaj baskısı", "Parlak yüzeylerde beyaz baskı"],
    ["UV lamba gücü ve hat hızı ürün performansını etkiler.", "Beyaz boya kalınlığı kürlenme süresiyle birlikte değerlendirilmelidir.", "Parlak yüzeylerde tutunma testi önerilir."],
    ["uv-beyaz-serigrafi-boyasi", "uv-kirmizi-serigrafi-murekkebi", "uv-siyah-serigrafi-boyasi"],
    uvRelated,
    ["uv-serigrafi-boyasi", "uv-kurumali-serigrafi-boyasi", "etiket-baski-boyasi"]
  ),
  productDetailPage(
    "uv-kirmizi-serigrafi-murekkebi",
    "UV Kırmızı Serigrafi Mürekkebi",
    "uv-serigrafi-boyalari",
    "UV Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "UV serigrafi mürekkebi",
    "Kırmızı",
    ["etiket", "ambalaj", "plastik", "cam", "metal", "promosyon"],
    ["Hızlı kürlenen kırmızı baskı", "Etiket ve ambalaj vurgusu", "Parlak yüzeylerde canlı renk uygulaması"],
    ["Kırmızı UV baskıda lamba gücü ve hat hızı kontrol edilmelidir.", "Renk standardı seri üretim öncesi numune ile doğrulanmalıdır.", "Boya kalınlığı kürlenme performansını etkiler."],
    ["uv-renkli-serigrafi-boyasi", "argon-105-101-uv-beyaz-serigrafi-boyasi", "uv-siyah-serigrafi-boyasi"],
    uvRelated,
    ["uv-serigrafi-boyasi", "uv-kurumali-serigrafi-boyasi", "ambalaj-baski-boyasi"]
  ),
  productDetailPage(
    "asit-maske-boyasi-27-401-argon-epta-nova",
    "27-401 Asit Maske Boyası Argon Epta Nova",
    "serigrafi-baski-boyalari",
    "Serigrafi Baskı Boyaları",
    "/products/uv-renkliler.jpeg",
    "Elektronik baskı devre asit maske boyası",
    "Etching resist",
    ["baskı devre", "bakır yüzey", "elektronik panel", "metal yüzey", "teknik üretim"],
    ["Baskı devre asit maskeleme", "Etching resist uygulaması", "Elektronik üretimde teknik koruma baskısı"],
    ["Asit maske uygulamasında proses ve kimyasal uyumu kritik önemdedir.", "Baskı kalınlığı ve kuruma/kürlenme süreci teknik gerekliliğe göre ayarlanmalıdır.", "Seri üretimden önce proses testi yapılmalıdır."],
    ["amex-bi-epoxi-serisi-siyah", "epoxer-92-101-beyaz-argon", "serigrafi-emulsiyonu"],
    serigrafiBaskiRelated,
    ["endustriyel-serigrafi-boyasi", "metal-serigrafi-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "zh-sertlestirici",
    "ZH Sertleştirici",
    "serigrafi-yardimci-kimyasallari",
    "Serigrafi Yardımcı Kimyasalları",
    "/products/sertlestirici.png",
    "Sertleştirici",
    "Dayanım desteği",
    ["epoksi boya", "cam baskı", "metal baskı", "alüminyum yüzey", "endüstriyel serigrafi"],
    ["Baskı dayanımını destekleme", "Cam ve metal boyalarında sertleşme desteği", "Yüzey performansını artırma"],
    ["Sertleştirici uyumlu boya sistemiyle kullanılmalıdır.", "Karışım oranı ve pot-life üretim öncesi netleştirilmelidir.", "Fazla veya eksik kullanım dayanım sonucunu etkileyebilir."],
    ["serigrafi-sertlestirici", "amex-bi-epoxi-serisi-siyah", "epoxser-beyaz-rz-101-cam-metal-aluminyum-boyasi"],
    ["sertlestirici-nasil-kullanilir", "serigrafi-boya-secimi", "serigrafi-baski-hatalari"],
    ["sertlestirici", "serigrafi-yardimci-kimyasallari", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "beyaz-baski-pati-matweisse-su-bazli",
    "Beyaz Baskı Patı Matweisse Su Bazlı",
    "su-bazli-serigrafi-boyalari",
    "Su Bazlı Serigrafi Boyaları",
    "/products/su-bazli-siyah-beyaz.jpeg",
    "Su bazlı beyaz baskı patı",
    "Beyaz",
    ["tişört", "pamuklu kumaş", "bez çanta", "promosyon tekstili", "tekstil aksesuarı"],
    ["Su bazlı beyaz tekstil baskı", "Açık renk kumaşlarda logo uygulaması", "Yumuşak tuşeli baskı"],
    ["Kumaş emiciliği beyaz görünümü etkileyebilir.", "Fikse koşulu yıkama dayanımı için önemlidir.", "Koyu kumaşlarda opaklık ve alt zemin ihtiyacı test edilmelidir."],
    ["su-bazli-beyaz-boya", "koyu-zemin-pati-su-bazli", "acik-zemin-pati-seffaf-su-bazli"],
    ["su-bazli-serigrafi-boyasi-nedir", "plastisol-vs-su-bazli-boya", "tekstil-baski-boyasi-secimi"],
    ["su-bazli-tekstil-boyasi", "tekstil-baski-boyasi", "emprime-baski-boyasi"]
  ),
  productDetailPage(
    "koyu-zemin-pati-su-bazli",
    "Koyu Zemin Patı Su Bazlı",
    "su-bazli-serigrafi-boyalari",
    "Su Bazlı Serigrafi Boyaları",
    "/products/su-bazli-siyah-beyaz.jpeg",
    "Su bazlı koyu zemin patı",
    "Renklendirilebilir pat",
    ["koyu kumaş", "tişört", "sweatshirt", "bez çanta", "promosyon tekstili"],
    ["Koyu kumaşta tekstil baskı", "Renklendirilebilir su bazlı baskı", "Yumuşak tuşeli emprime uygulaması"],
    ["Koyu zeminde örtücülük numune ile kontrol edilmelidir.", "Renklendirme oranı ve pigment uyumu sonucu etkiler.", "Doğru fikse yıkama dayanımı için gereklidir."],
    ["beyaz-baski-pati-matweisse-su-bazli", "acik-zemin-pati-seffaf-su-bazli", "su-bazli-siyah-boya"],
    ["su-bazli-serigrafi-boyasi-nedir", "tekstil-baski-boyasi-secimi", "plastisol-vs-su-bazli-boya"],
    ["su-bazli-tekstil-boyasi", "tekstil-baski-boyasi", "emprime-baski-boyasi"]
  ),
  productDetailPage(
    "acik-zemin-pati-seffaf-su-bazli",
    "Açık Zemin Patı Şeffaf Su Bazlı",
    "su-bazli-serigrafi-boyalari",
    "Su Bazlı Serigrafi Boyaları",
    "/products/su-bazli-siyah-beyaz.jpeg",
    "Su bazlı açık zemin patı",
    "Şeffaf pat",
    ["açık renk kumaş", "tişört", "bez çanta", "promosyon tekstili", "pamuklu kumaş"],
    ["Açık renk kumaşta su bazlı baskı", "Yumuşak tuşeli tekstil uygulaması", "Renklendirilebilir şeffaf pat baskısı"],
    ["Açık zeminde kumaş rengi nihai tonu etkileyebilir.", "Pigment oranı ve pat uyumu üretim öncesi test edilmelidir.", "Kurutma ve fikse standardı kayıt altına alınmalıdır."],
    ["beyaz-baski-pati-matweisse-su-bazli", "koyu-zemin-pati-su-bazli", "su-bazli-beyaz-boya"],
    ["su-bazli-serigrafi-boyasi-nedir", "tekstil-baski-boyasi-secimi", "plastisol-vs-su-bazli-boya"],
    ["su-bazli-tekstil-boyasi", "tekstil-baski-boyasi", "emprime-baski-boyasi"]
  ),
];

export const productDetailPages: ProductDetailPage[] = [
  ...listedSerigrafiProductPages,
  productDetailPage(
    "pvc-altin-yaldiz-serigrafi-boyasi",
    "PVC Altın Yaldız Serigrafi Boyası",
    "pvc-yaldiz-boyalari",
    "PVC Yaldız Boyaları",
    "/products/pvc-altin-yaldiz.png",
    "PVC bazlı serigrafi boyası",
    "Altın yaldız",
    ["PVC", "suni deri", "karton", "etiket", "premium ambalaj", "promosyon ürünleri"],
    ["Metalik altın efektli logo ve dekoratif baskı", "Premium ambalaj baskısı", "Suni deri ve PVC üstü marka uygulaması"],
    ["Yaldız pigmenti homojen karıştırılmalıdır.", "Yüzey temizliği tutunma performansını doğrudan etkiler.", "Seri üretim öncesi küçük numune baskı önerilir."],
    ["pvc-gumus-yaldiz-serigrafi-boyasi", "pvc-beyaz-serigrafi-boyasi", "serigrafi-inceltici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "pvc-baski-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-gumus-yaldiz-serigrafi-boyasi",
    "PVC Gümüş Yaldız Serigrafi Boyası",
    "pvc-yaldiz-boyalari",
    "PVC Yaldız Boyaları",
    "/products/pvc-gumus-yaldiz.png",
    "PVC bazlı serigrafi boyası",
    "Gümüş yaldız",
    ["PVC", "suni deri", "etiket", "ambalaj", "dekoratif plastik", "karton"],
    ["Gümüş metalik efektli baskı", "Dekoratif marka uygulaması", "Etiket ve ambalaj vurgusu"],
    ["Baskıdan önce boya karışımı stabil hale getirilmelidir.", "İnce detaylarda elek ve rakle seçimi önemlidir.", "Kuruma ve yüzey dayanımı test edilmelidir."],
    ["pvc-altin-yaldiz-serigrafi-boyasi", "pvc-siyah-serigrafi-boyasi", "serigrafi-sertlestirici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "pvc-baski-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-beyaz-serigrafi-boyasi",
    "PVC Beyaz Serigrafi Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/pvc-gumus-yaldiz.png",
    "PVC serigrafi boyası",
    "Beyaz",
    ["PVC", "plastik", "suni deri", "etiket", "ambalaj", "promosyon"],
    ["Opak beyaz logo baskısı", "Zemin hazırlığı ve alt baskı", "Plastik ve PVC yüzey işaretleme"],
    ["Beyaz tonlarda örtücülük beklentisi netleştirilmelidir.", "Yüzey enerjisi düşük plastiklerde test baskısı yapılmalıdır.", "Viskozite uygulama hızına göre ayarlanmalıdır."],
    ["pvc-siyah-serigrafi-boyasi", "pvc-kirmizi-serigrafi-boyasi", "serigrafi-inceltici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "plastik-serigrafi-boyasi", "pvc-serigrafi-boyasi-fiyatlari"]
  ),
  productDetailPage(
    "pvc-siyah-serigrafi-boyasi",
    "PVC Siyah Serigrafi Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/pvc-gumus-yaldiz.png",
    "PVC serigrafi boyası",
    "Siyah",
    ["PVC", "plastik", "suni deri", "etiket", "karton", "ambalaj"],
    ["Net siyah logo ve yazı baskısı", "Teknik işaretleme", "Ambalaj ve etiket baskısı"],
    ["Siyah baskıda çizgi netliği için elek seçimi önemlidir.", "Yüzey temizliği baskı dayanımını artırır.", "Kuruma davranışı üretim temposuna göre planlanmalıdır."],
    ["pvc-beyaz-serigrafi-boyasi", "pvc-mavi-serigrafi-boyasi", "serigrafi-geciktirici"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "plastik-serigrafi-boyasi", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-kirmizi-serigrafi-boyasi",
    "PVC Kırmızı Serigrafi Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/pvc-altin-yaldiz.png",
    "PVC serigrafi boyası",
    "Kırmızı",
    ["PVC", "plastik", "etiket", "ambalaj", "promosyon", "suni deri"],
    ["Kırmızı marka rengi baskısı", "Promosyon ve etiket baskısı", "Dikkat çekici ambalaj uygulaması"],
    ["Kurumsal renk beklentisi varsa numune ile eşleştirme yapılmalıdır.", "Renk doygunluğu baskı kalınlığıyla birlikte değerlendirilmelidir.", "Seri üretimde karıştırma standardı korunmalıdır."],
    ["pvc-beyaz-serigrafi-boyasi", "pvc-mavi-serigrafi-boyasi", "pvc-sari-serigrafi-boyasi"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "promosyon-baski-boyasi", "etiket-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-mavi-serigrafi-boyasi",
    "PVC Mavi Serigrafi Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "PVC serigrafi boyası",
    "Mavi",
    ["PVC", "plastik", "etiket", "ambalaj", "teknik parça", "promosyon"],
    ["Mavi logo ve marka baskısı", "Teknik yüzey işaretleme", "Promosyon ürün baskısı"],
    ["Mavi ton standardı sipariş öncesinde netleştirilmelidir.", "Parlak yüzeylerde tutunma testi önerilir.", "Viskozite ve kuruma süresi üretim hızına göre ayarlanmalıdır."],
    ["pvc-kirmizi-serigrafi-boyasi", "pvc-siyah-serigrafi-boyasi", "pvc-sari-serigrafi-boyasi"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "plastik-serigrafi-boyasi", "pvc-baski-boyasi"]
  ),
  productDetailPage(
    "pvc-sari-serigrafi-boyasi",
    "PVC Sarı Serigrafi Boyası",
    "pvc-serigrafi-boyalari",
    "PVC Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "PVC serigrafi boyası",
    "Sarı",
    ["PVC", "plastik", "ambalaj", "etiket", "levha", "promosyon"],
    ["Sarı logo ve uyarı baskısı", "Etiket ve ambalaj renklendirme", "Dekoratif PVC yüzey uygulaması"],
    ["Sarı tonlarda örtücülük yüzeye göre değerlendirilmelidir.", "Açık renklerde zemin etkisi dikkate alınmalıdır.", "Seri üretim öncesi kuruma ve tutunma testi yapılmalıdır."],
    ["pvc-kirmizi-serigrafi-boyasi", "pvc-mavi-serigrafi-boyasi", "pvc-beyaz-serigrafi-boyasi"],
    pvcRelated,
    ["pvc-serigrafi-boyasi", "etiket-baski-boyasi", "serigrafi-boya-fiyatlari"]
  ),
  productDetailPage(
    "emprime-baski-boyasi",
    "Emprime Baskı Boyası",
    "emprime-baski-boyalari",
    "Emprime Baskı Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil emprime baskı boyası",
    "Renkli / özel renk",
    ["tişört", "sweatshirt", "pamuklu kumaş", "bez çanta", "promosyon tekstili", "transfer baskı"],
    ["Tekstil üzerine emprime baskı", "Tişört ve kumaş logo baskısı", "Transfer ve serigrafi baskı uygulaması"],
    ["Kumaş tipi ve hedef tuşe ürün seçimini etkiler.", "Fikse ve kurutma koşulu yıkama dayanımı için kontrol edilmelidir.", "Koyu kumaşlarda opaklık ve alt zemin ihtiyacı test edilmelidir."],
    ["plastisol-beyaz-boya", "plastisol-siyah-boya", "su-bazli-beyaz-boya"],
    ["tekstil-baski-boyasi-secimi", "plastisol-boya-nedir", "plastisol-vs-su-bazli-boya"],
    ["emprime-baski-boyasi", "tekstil-baski-boyasi", "plastisol-boya"]
  ),
  productDetailPage(
    "plastisol-beyaz-boya",
    "Plastisol Beyaz Boya",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol boyası",
    "Beyaz",
    ["tişört", "sweatshirt", "pamuklu kumaş", "bez çanta", "promosyon tekstili"],
    ["Opak beyaz tekstil baskısı", "Koyu kumaşlarda alt zemin", "Tişört ve sweatshirt logo baskısı"],
    ["Fikse koşulu yıkama dayanımını belirler.", "Koyu kumaşta örtücülük beklentisi netleştirilmelidir.", "Baskı kalınlığı ve tuşe hissi birlikte planlanmalıdır."],
    ["plastisol-siyah-boya", "plastisol-kirmizi-boya", "plastisol-altin-yaldiz"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-baski-boyasi", "tisort-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-siyah-boya",
    "Plastisol Siyah Boya",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol boyası",
    "Siyah",
    ["tişört", "sweatshirt", "bez çanta", "pamuklu kumaş", "iş kıyafeti"],
    ["Siyah tekstil logo baskısı", "Net yazı ve grafik baskısı", "Seri tişört üretimi"],
    ["Siyah baskıda netlik için rakle basıncı önemlidir.", "Fikse standardı kayıt altına alınmalıdır.", "Kumaş tipi ürün seçimini etkileyebilir."],
    ["plastisol-beyaz-boya", "plastisol-mavi-boya", "plastisol-gumus-yaldiz"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-serigrafi-boyasi", "tekstil-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-kirmizi-boya",
    "Plastisol Kırmızı Boya",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol boyası",
    "Kırmızı",
    ["tişört", "sweatshirt", "bez çanta", "promosyon tekstili", "pamuklu kumaş"],
    ["Canlı kırmızı tekstil baskısı", "Kurumsal renk uygulaması", "Promosyon tişört baskısı"],
    ["Kurumsal ton beklentisi varsa numune üzerinden ilerlenmelidir.", "Fikse ve yıkama testi önerilir.", "Renk canlılığı baskı kalınlığıyla birlikte değerlendirilir."],
    ["plastisol-beyaz-boya", "plastisol-mavi-boya", "plastisol-sari-boya"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-baski-boyasi", "tisort-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-mavi-boya",
    "Plastisol Mavi Boya",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol boyası",
    "Mavi",
    ["tişört", "sweatshirt", "bez çanta", "promosyon tekstili", "tekstil aksesuarı"],
    ["Mavi logo baskısı", "Marka rengi uygulaması", "Seri tekstil baskısı"],
    ["Mavi ton standardı üretim öncesi netleştirilmelidir.", "Kumaş rengi nihai sonucu etkileyebilir.", "Fikse koşulu dayanım için kritiktir."],
    ["plastisol-kirmizi-boya", "plastisol-siyah-boya", "plastisol-sari-boya"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-serigrafi-boyasi", "tekstil-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-sari-boya",
    "Plastisol Sarı Boya",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol boyası",
    "Sarı",
    ["tişört", "sweatshirt", "bez çanta", "iş kıyafeti", "promosyon tekstili"],
    ["Sarı tekstil baskısı", "Uyarı ve dikkat renkli baskı", "Promosyon kumaş uygulaması"],
    ["Açık renk tonlarda zemin etkisi dikkate alınmalıdır.", "Örtücülük ve tuşe dengesi birlikte planlanmalıdır.", "Yıkama dayanımı için doğru fikse gerekir."],
    ["plastisol-kirmizi-boya", "plastisol-mavi-boya", "plastisol-beyaz-boya"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-baski-boyasi", "tisort-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-altin-yaldiz",
    "Plastisol Altın Yaldız",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol efekti",
    "Altın yaldız",
    ["tişört", "sweatshirt", "promosyon tekstili", "bez çanta", "tekstil aksesuarı"],
    ["Altın efektli tekstil baskısı", "Premium marka uygulaması", "Dekoratif tekstil grafiği"],
    ["Efekt baskılarda karıştırma standardı önemlidir.", "Fikse ve yıkama dayanımı test edilmelidir.", "Baskı kalınlığı görsel etkiyi değiştirebilir."],
    ["plastisol-gumus-yaldiz", "plastisol-beyaz-boya", "plastisol-siyah-boya"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-baski-boyasi", "promosyon-baski-boyasi"]
  ),
  productDetailPage(
    "plastisol-gumus-yaldiz",
    "Plastisol Gümüş Yaldız",
    "plastisol-boyalari",
    "Plastisol Boyaları",
    "/products/plastisol-cesitleri.png",
    "Tekstil plastisol efekti",
    "Gümüş yaldız",
    ["tişört", "sweatshirt", "promosyon tekstili", "bez çanta", "tekstil aksesuarı"],
    ["Gümüş efektli tekstil baskısı", "Premium logo baskısı", "Dekoratif tekstil uygulaması"],
    ["Metalik etki için homojen karışım gerekir.", "Kumaş ve yıkama koşulu birlikte değerlendirilmelidir.", "Numune baskı ürün seçimini netleştirir."],
    ["plastisol-altin-yaldiz", "plastisol-siyah-boya", "plastisol-beyaz-boya"],
    plastisolRelated,
    ["plastisol-boya", "tekstil-baski-boyasi", "promosyon-baski-boyasi"]
  ),
  productDetailPage(
    "uv-beyaz-serigrafi-boyasi",
    "UV Beyaz Serigrafi Boyası",
    "uv-serigrafi-boyalari",
    "UV Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "UV kurumalı serigrafi boyası",
    "Beyaz",
    ["etiket", "ambalaj", "plastik", "cam", "metal", "promosyon ürünleri"],
    ["Hızlı kürlenen beyaz baskı", "Etiket ve ambalaj uygulaması", "Parlak yüzeylerde logo baskısı"],
    ["UV lamba gücü ve hat hızı kontrol edilmelidir.", "Boya kalınlığı kürlenmeyi etkiler.", "Yüzey tutunma testi önerilir."],
    ["uv-siyah-serigrafi-boyasi", "uv-renkli-serigrafi-boyasi", "serigrafi-sertlestirici"],
    uvRelated,
    ["uv-serigrafi-boyasi", "uv-kurumali-serigrafi-boyasi", "etiket-baski-boyasi"]
  ),
  productDetailPage(
    "uv-siyah-serigrafi-boyasi",
    "UV Siyah Serigrafi Boyası",
    "uv-serigrafi-boyalari",
    "UV Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "UV kurumalı serigrafi boyası",
    "Siyah",
    ["etiket", "ambalaj", "plastik", "cam", "metal", "promosyon ürünleri"],
    ["Hızlı kürlenen siyah baskı", "Net yazı ve logo uygulaması", "Endüstriyel yüzey işaretleme"],
    ["UV sistem ayarı baskı dayanımını belirler.", "Parlak yüzeylerde ön test yapılmalıdır.", "İnce detaylarda elek seçimi önemlidir."],
    ["uv-beyaz-serigrafi-boyasi", "uv-renkli-serigrafi-boyasi", "serigrafi-inceltici"],
    uvRelated,
    ["uv-serigrafi-boyasi", "uv-kurumali-serigrafi-boyasi", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "uv-renkli-serigrafi-boyasi",
    "UV Renkli Serigrafi Boyası",
    "uv-serigrafi-boyalari",
    "UV Serigrafi Boyaları",
    "/products/uv-renkliler.jpeg",
    "UV kurumalı serigrafi boyası",
    "Renkli seri",
    ["etiket", "ambalaj", "plastik", "cam", "metal", "promosyon"],
    ["Renkli UV baskı", "Hızlı üretim hattı uygulaması", "Parlak ve net marka baskısı"],
    ["Renk seçimi yüzey ve UV sistemle birlikte değerlendirilmelidir.", "Kürlenme testleri seri üretim öncesinde yapılmalıdır.", "Düzenli üretimde renk standardı korunmalıdır."],
    ["uv-beyaz-serigrafi-boyasi", "uv-siyah-serigrafi-boyasi", "serigrafi-geciktirici"],
    uvRelated,
    ["uv-serigrafi-boyasi", "etiket-baski-boyasi", "ambalaj-baski-boyasi"]
  ),
  productDetailPage(
    "su-bazli-siyah-boya",
    "Su Bazlı Siyah Boya",
    "su-bazli-serigrafi-boyalari",
    "Su Bazlı Serigrafi Boyaları",
    "/products/su-bazli-siyah-beyaz.jpeg",
    "Su bazlı tekstil boyası",
    "Siyah",
    ["pamuklu kumaş", "tişört", "bez çanta", "tekstil aksesuarı", "promosyon tekstili"],
    ["Yumuşak tuşeli siyah baskı", "Tekstil logo uygulaması", "Doğal hissi koruyan baskı"],
    ["Kumaş emiciliği sonucu etkiler.", "Kuruma ve fikse koşulları kontrol edilmelidir.", "Su bazlı sistemlerde kalıp temizliği önemlidir."],
    ["su-bazli-beyaz-boya", "plastisol-siyah-boya", "serigrafi-emulsiyonu"],
    ["su-bazli-serigrafi-boyasi-nedir", "plastisol-vs-su-bazli-boya", "tekstil-baski-boyasi-secimi"],
    ["su-bazli-tekstil-boyasi", "su-bazli-serigrafi-boyasi", "tekstil-baski-boyasi"]
  ),
  productDetailPage(
    "su-bazli-beyaz-boya",
    "Su Bazlı Beyaz Boya",
    "su-bazli-serigrafi-boyalari",
    "Su Bazlı Serigrafi Boyaları",
    "/products/su-bazli-siyah-beyaz.jpeg",
    "Su bazlı tekstil boyası",
    "Beyaz",
    ["pamuklu kumaş", "tişört", "bez çanta", "tekstil aksesuarı", "promosyon tekstili"],
    ["Yumuşak tuşeli beyaz baskı", "Tekstil logo ve grafik uygulaması", "Doğal hisli açık renk baskı"],
    ["Beyaz tonlarda kumaş rengi sonucu etkileyebilir.", "Fikse koşulu dayanım için önemlidir.", "Numune baskı ile örtücülük kontrol edilmelidir."],
    ["su-bazli-siyah-boya", "plastisol-beyaz-boya", "serigrafi-emulsiyonu"],
    ["su-bazli-serigrafi-boyasi-nedir", "plastisol-vs-su-bazli-boya", "tekstil-baski-boyasi-secimi"],
    ["su-bazli-tekstil-boyasi", "su-bazli-serigrafi-boyasi", "tekstil-baski-boyasi"]
  ),
  productDetailPage(
    "serigrafi-emulsiyonu",
    "Serigrafi Emülsiyonu",
    "serigrafi-emulsiyonlari",
    "Serigrafi Emülsiyonları",
    "/products/emulsiyon.png",
    "Fotoemülsiyon",
    "Kalıp hazırlama",
    ["ipek kalıp", "polyester elek", "tekstil kalıbı", "ambalaj baskı kalıbı", "grafik baskı kalıbı"],
    ["Serigrafi kalıbı hazırlama", "Net desen oluşturma", "Baskı öncesi şablon üretimi"],
    ["Elek numarası ve boya tipi birlikte değerlendirilmelidir.", "Pozlama süresi kalıp netliğini belirler.", "Kalıp tamamen kuruduktan sonra pozlama yapılmalıdır."],
    ["emulsiyon-sokucu", "serigrafi-inceltici", "aluminyum-ragle"],
    chemicalRelated,
    ["serigrafi-emulsiyonu", "emulsiyon", "serigrafi-yardimci-kimyasallari"]
  ),
  productDetailPage(
    "emulsiyon-sokucu",
    "Emülsiyon Sökücü",
    "serigrafi-emulsiyonlari",
    "Serigrafi Emülsiyonları",
    "/products/emulsiyon-sokucu.png",
    "Kalıp temizleme kimyasalı",
    "Temizleme",
    ["ipek kalıp", "polyester elek", "tekstil kalıbı", "ambalaj baskı kalıbı", "serigrafi çerçevesi"],
    ["Eski emülsiyon temizleme", "Kalıp yenileme", "Şablon tekrar kullanımı"],
    ["Uygulama süresi kalıntı yoğunluğuna göre değişebilir.", "Kalıp temizliği sonrası durulama önemlidir.", "Düzenli kullanım kalıp verimliliğini artırabilir."],
    ["serigrafi-emulsiyonu", "serigrafi-inceltici", "serigrafi-ragle-lastigi"],
    ["emulsiyon-sokucu-nedir", "serigrafi-kalip-hazirlama", "emulsiyon-nasil-kullanilir"],
    ["emulsiyon-sokucu", "serigrafi-yardimci-kimyasallari", "serigrafi-kimyasallari"]
  ),
  productDetailPage(
    "serigrafi-inceltici",
    "Serigrafi İnceltici",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "Yardımcı kimyasal",
    "Viskozite ayarı",
    ["PVC baskı", "plastik baskı", "tekstil baskı", "ambalaj baskı", "serigrafi atölyesi"],
    ["Boya viskozitesini ayarlama", "Akış kontrolü", "Uygulama rahatlığı sağlama"],
    ["İnceltici kontrollü kullanılmalıdır.", "Ürün tipi ve yüzey bilgisi dikkate alınmalıdır.", "Fazla kullanım renk ve tutunma karakterini değiştirebilir."],
    ["serigrafi-geciktirici", "serigrafi-sertlestirici", "pvc-beyaz-serigrafi-boyasi"],
    ["serigrafi-boyasi-nasil-inceltilir", "serigrafi-baski-hatalari", "serigrafi-boya-secimi"],
    ["inceltici", "serigrafi-yardimci-kimyasallari", "serigrafi-kimyasallari"]
  ),
  productDetailPage(
    "serigrafi-geciktirici",
    "Serigrafi Geciktirici",
    "serigrafi-inceltici-geciktirici",
    "İnceltici ve Geciktirici",
    "/products/inceltici.png",
    "Yardımcı kimyasal",
    "Kuruma kontrolü",
    ["PVC baskı", "plastik baskı", "tekstil baskı", "ambalaj baskı", "serigrafi kalıbı"],
    ["Kuruma süresini kontrol etme", "Kalıp tıkanmasını azaltma", "Sıcak ortamda baskı akışını rahatlatma"],
    ["Geciktirici ölçülü kullanılmalıdır.", "Ortam sıcaklığı ve baskı hızı dikkate alınmalıdır.", "Fazla kullanım kuruma süresini gereğinden fazla uzatabilir."],
    ["serigrafi-inceltici", "serigrafi-sertlestirici", "pvc-siyah-serigrafi-boyasi"],
    ["geciktirici-ne-ise-yarar", "serigrafi-baski-hatalari", "serigrafi-boyasi-nasil-inceltilir"],
    ["geciktirici", "serigrafi-yardimci-kimyasallari", "serigrafi-kimyasallari"]
  ),
  productDetailPage(
    "serigrafi-sertlestirici",
    "Serigrafi Sertleştirici",
    "serigrafi-yardimci-kimyasallari",
    "Serigrafi Yardımcı Kimyasalları",
    "/products/sertlestirici.png",
    "Yardımcı kimyasal",
    "Dayanım desteği",
    ["PVC baskı", "plastik baskı", "metal yüzey", "cam yüzey", "endüstriyel baskı"],
    ["Baskı dayanımını destekleme", "Yüzey performansı artırma", "Tutunma beklentisi yüksek işlerde yardımcı kullanım"],
    ["Sertleştirici uyumlu boya sistemiyle kullanılmalıdır.", "Karışım oranı teknik beklentiye göre değerlendirilmelidir.", "Uygulama öncesi test baskısı önerilir."],
    ["serigrafi-inceltici", "serigrafi-geciktirici", "uv-siyah-serigrafi-boyasi"],
    ["sertlestirici-nasil-kullanilir", "serigrafi-baski-hatalari", "serigrafi-boya-secimi"],
    ["sertlestirici", "serigrafi-yardimci-kimyasallari", "endustriyel-serigrafi-boyasi"]
  ),
  productDetailPage(
    "aluminyum-ragle",
    "Alüminyum Ragle",
    "serigrafi-baski-malzemeleri",
    "Serigrafi Baskı Malzemeleri",
    "/products/ragle-cekcek.png",
    "Baskı ekipmanı",
    "Alüminyum gövde",
    ["serigrafi kalıbı", "tekstil baskı", "PVC baskı", "ambalaj baskı", "atölye üretimi"],
    ["Boya transferini kontrol etme", "Baskı basıncını dengeleme", "Manuel ve yarı otomatik uygulamalarda kullanım"],
    ["Ragle sertliği ve açısı baskı karakterini etkiler.", "Boya transferi için basınç dengesi önemlidir.", "Ölçü seçimi kalıp ve baskı alanına göre yapılmalıdır."],
    ["serigrafi-ragle-lastigi", "serigrafi-emulsiyonu", "serigrafi-inceltici"],
    ["ragle-nedir", "serigrafi-baski-teknikleri", "ipek-kalip-nedir"],
    ["serigrafi-yardimci-malzemeleri", "serigrafi-malzemeleri", "serigrafi-baski-boyasi"]
  ),
  productDetailPage(
    "serigrafi-ragle-lastigi",
    "Serigrafi Ragle Lastiği",
    "serigrafi-baski-malzemeleri",
    "Serigrafi Baskı Malzemeleri",
    "/products/ragle-cekcek.png",
    "Baskı ekipmanı",
    "Ragle lastiği",
    ["serigrafi kalıbı", "tekstil baskı", "PVC baskı", "ambalaj baskı", "grafik baskı"],
    ["Boya transferi kontrolü", "Baskı netliği sağlama", "Atölye ekipman yenileme"],
    ["Ragle lastiği sertliği baskıdaki boya geçişini etkiler.", "Aşınmış lastik çizgi netliğini bozabilir.", "Baskı yüzeyine ve boya tipine göre seçim yapılmalıdır."],
    ["aluminyum-ragle", "serigrafi-emulsiyonu", "serigrafi-inceltici"],
    ["ragle-nedir", "serigrafi-baski-teknikleri", "serigrafi-baski-hatalari"],
    ["serigrafi-yardimci-malzemeleri", "serigrafi-malzemeleri", "serigrafi-baski-boyasi"]
  ),
];

export const productDetailPageMap = new Map(
  productDetailPages.map((page) => [page.slug, page])
);

export const productDetailPageMapByTitle = new Map(
  productDetailPages.map((page) => [page.focusKeyword, page])
);
